image: docker:19.03.8

services:
  - docker:19.03.8-dind

variables:
  DOCKER_TLS_CERTDIR: "/certs"

stages:
  - Build php images

before_script:
  - docker info

docker build:
  stage: Build php images
  only:
    - master
  variables:
    VERSION_LIST: "5.6 7.0 7.1 7.2 7.3"
  script:
    - /bin/sh ./scripts/build.sh --push
