image: docker:19.03.8

services:
  - docker:19.03.8-dind

stages:
  - Build php images

before_script:
  - docker info
  - apk update && apk add bash

docker build:
  stage: Build php images
  only:
    - schedules
  variables:
    VERSION_LIST: "5.6 7.0 7.1 7.2 7.3"
  script:
    - ./scripts/build.sh --push
