image: docker:latest

services:
  - docker:dind

stages:
  - Build php images

before_script:
  - docker info
  - apk update && apk add bash

docker build:
  stage: Build php images
  only:
    - schedules
  script:
    - ./scripts/build.sh --push
